version: '2'

services:
  combishackaton:
    image: combishackaton
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - .:/usr/src/app:ro
      - node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 80:3000
    depends_on: 
        - mongo
    networks: 
      backend:

  mongo:
    image: mongo:3.7-jessie
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASS}
      MONGO_LOG_DIR: "/data/log"
      MONGO_DATA_DIR: "/data/db"
    volumes:
      - database:/data/db
    expose:
      - "27017"
      
    networks:
      backend:
        aliases: 
          - ${MONGO_NETWORK_ALIAS}

  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - 8081:8081
    networks: 
      - backend
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASS}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_NETWORK_ALIAS}
    depends_on:
      - mongo
      - combishackaton
    command: tini -- bash -c 'sleep 5 && node app'
networks: 
  backend:
volumes:
  node_modules:
  database:
