FROM node:9.11 

ENV NODE_ENV production
WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent -g nodemon
RUN npm install --production --silent && mv node_modules ../
EXPOSE 3000
CMD nodemon